export default {
    orange: '#EC8134',
    orangeLighter: '#FFD6B9',
    anotherOrange: '#F29D60B2',
    orangeDarker: '#CF5B07',
    red: '#DD5454',
    redDarker: '#C02C2C',
    white: '#FEFEFE',
    gray: '#D9D9D9',
    grayLighter: '#F2F2F2',
    grayDarker: '#D2D2D2',
    anotherGrayDarker: '#8B8B8B',
    textLight: '#FEFEFE',
    textDark: '#1E1E1E',
}